# Generated by Django 5.0.7 on 2024-07-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
    ]
