# Generated by Django 5.0.7 on 2024-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_movie_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_cnt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
